### ISSUE TITLE
Sdk Installed

### ISSUE THREAD

**Issue by hfiguiere** [flathub/com.gitlab.JakobDev.jdAppdataEdit#17]
Why does this package install the SDK?

**Comment by JakobDev** [comment]
It does need git to import releases from a git repo (see [source](https://gitlab.com/JakobDev/jdAppdataEdit/-/blob/fc67f7771551fc6643048eb0be66dc87c5c6fa05/jdAppdataEdit/ReleaseImporter.py#L106)). And git is only included in the SDK and not in the Platform.

**Comment by hfiguiere** [comment]
What other package do is the build git. And you should too.

**Comment by JakobDev** [comment]
But why? Why should I waste my time maintaining and resources of the Buildserver every time I rebuild if there is a working git?

**Comment by hfiguiere** [comment]
the build server are NOT a concern. 

The rest, it's just your convenience vs the user, I guess, user that will have to download 600MB eventually to use the app. I had to, in my case.

**Comment by JakobDev** [comment]
Have you a example for a App that build git by source? I tried it, but it crashes the builder:
```yaml
  - name: git
    sources:
      - type: archive
        url: https://www.kernel.org/pub/software/scm/git/git-2.37.1.tar.gz
        sha256: 7dded96a52e7996ce90dd74a187aec175737f680dc063f3f33c8932cf5c8d809
```
The term `git` is quite common in Manifests, so the search doesn't help.

**Comment by bilelmoussaoui** [comment]
You can copy git from the SDK, see what Meld does.

**Comment by hfiguiere** [comment]
FreeCAD does

**Comment by JakobDev** [comment]
Meld just copies the git binary, which does not vrella work. I have now try to include the git manifest from FeeCAD.
```yaml
app-id: com.gitlab.JakobDev.jdAppdataEdit
runtime: org.kde.Platform
runtime-version: '6.3'
sdk: org.kde.Sdk
base: com.riverbankcomputing.PyQt.BaseApp
base-version: '6.3'
command: jdappdataedit
cleanup-commands:
  - /app/cleanup-BaseApp.sh
build-options:
  env:
    - BASEAPP_REMOVE_PYWEBENGINE=1
finish-args:
  - --socket=fallback-x11
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --share=network
  # For preview in Gnome Software
  - --talk-name=org.freedesktop.Flatpak

modules:
  - python3-modules.json

  - name: git
    make-args:
      - NO_TCLTK=YesPlease
      - INSTALL_SYMLINKS=1
    make-install-args:
      - NO_TCLTK=YesPlease
      - INSTALL_SYMLINKS=1
    post-install:
      - find . -type f -name perllocal.pod -delete
    sources:
      - type: archive
        url: https://www.kernel.org/pub/software/scm/git/git-2.28.0.tar.gz
        sha256: f914c60a874d466c1e18467c864a910dd4ea22281ba6d4d58077cb0c3f115170

  - name: jdAppdataEdit
    buildsystem: simple
    build-commands:
      - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
      - install -Dm644 jdAppdataEdit/Icon.svg $FLATPAK_DEST/share/icons/hicolor/scalable/apps/com.gitlab.JakobDev.jdAppdataEdit.svg
      - install -Dm644 Deploy/com.gitlab.JakobDev.jdAppdataEdit.desktop $FLATPAK_DEST/share/applications/com.gitlab.JakobDev.jdAppdataEdit.desktop
      - install -Dm644 Deploy/com.gitlab.JakobDev.jdAppdataEdit.metainfo.xml $FLATPAK_DEST/share/metainfo/com.gitlab.JakobDev.jdAppdataEdit.metainfo.xml
      - install -Dm644 Deploy/x-freedesktop-appstream.xml $FLATPAK_DEST/share/mime/packages/com.gitlab.JakobDev.jdAppdataEdit.xml
    sources:
      - type: git
        url: https://gitlab.com/JakobDev/jdAppdataEdit.git
        tag: '4.2'
        commit: d5198b61f82d84e91bc6a5f5ce7a98b3944ce443
        x-checker-data:
          type: git
```
When build with `flatpak run org.flatpak.Builder  build-dir com.gitlab.JakobDev.jdAppdataEdit.yml --force-clean --ccache --install --user` this results reproduceable in a endlessloop when the builder tries to strip the debug symbols.
